Repository jenkinsci/parallel-test-executor-plugin, pull requests merged in 2020-03, with the labels that each got.

#100 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  pom.xml
Labels: bug

#90 Migrate Jenkins Wiki Content to GitHub README
  README.md
  pom.xml
Labels: documentation

#106 Enable Release Drafter
  .github/release-drafter.yml
  README.md
  old-changelog.md
Labels: documentation

#104 POM updates
  pom.xml
Labels: dependencies

#107 Demo update
  demo/Dockerfile
  demo/JENKINS_HOME/config.xml
  demo/JENKINS_HOME/maven-settings-files.xml
  demo/pom.xml
Labels: documentation

#108 Not intending to push the demo to Hub
  demo/Makefile
  demo/README.md
Labels: documentation
