Repository jenkinsci/parallel-test-executor-plugin, pull requests merged in 2022-04, with the labels that each got.

#179 Set up JEP-229
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/release-drafter.yml
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: chore

#186 Execute regex - fixes estimateTestsFromFiles
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutor.java
Labels: bug

#189 Update POM & GHA, test on Java 17
  .github/workflows/cd.yml
  Jenkinsfile
  pom.xml
Labels: dependencies
