Repository jenkinsci/parallel-test-executor-plugin, pull requests merged in 2024-03, with the labels that each got.

#280 Miscellaneous refreshes of metadata files
  .github/CODEOWNERS
  .github/release-drafter.yml
  README.md
  old-changelog.md
  src/main/resources/index.jelly
Labels: chore

#279 Parallelize per java test case
  demo/repos/demo/Jenkinsfile
  demo/repos/demo/goodbye/pom.xml
  demo/repos/demo/hello/pom.xml
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutor.java
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/TestEntity.java
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/testmode/JavaClassName.java
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/testmode/JavaTestCaseName.java
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/testmode/TestMode.java
  src/main/resources/org/jenkinsci/plugins/parallel_test_executor/testmode/JavaTestCaseName/help.html
  src/test/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest.java
Labels: enhancement

#281 Make sure there are no duplicate cases
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/testmode/JavaClassName.java
  src/test/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest.java
  src/test/resources/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest/findTestDuplicates/report-Test1-bis.xml
  src/test/resources/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest/findTestDuplicates/report-Test1.xml
Labels: bug

#282 Defending against corrupt builds
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutor.java
Labels: bug

#283 Remove parameters from test case name
  src/main/java/org/jenkinsci/plugins/parallel_test_executor/testmode/JavaClassName.java
  src/test/java/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest.java
  src/test/resources/org/jenkinsci/plugins/parallel_test_executor/ParallelTestExecutorUnitTest/findTestCasesWithParameters/report-Test1.xml
Labels: bug
